package green;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.greendao.demo.entity.TestBean;
import com.greendao.demo.entity.User;
import com.greendao.demo.entity.GreenDaoBean;

import green.TestBeanDao;
import green.UserDao;
import green.GreenDaoBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig testBeanDaoConfig;
    private final DaoConfig userDaoConfig;
    private final DaoConfig greenDaoBeanDaoConfig;

    private final TestBeanDao testBeanDao;
    private final UserDao userDao;
    private final GreenDaoBeanDao greenDaoBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        testBeanDaoConfig = daoConfigMap.get(TestBeanDao.class).clone();
        testBeanDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        greenDaoBeanDaoConfig = daoConfigMap.get(GreenDaoBeanDao.class).clone();
        greenDaoBeanDaoConfig.initIdentityScope(type);

        testBeanDao = new TestBeanDao(testBeanDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);
        greenDaoBeanDao = new GreenDaoBeanDao(greenDaoBeanDaoConfig, this);

        registerDao(TestBean.class, testBeanDao);
        registerDao(User.class, userDao);
        registerDao(GreenDaoBean.class, greenDaoBeanDao);
    }
    
    public void clear() {
        testBeanDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
        greenDaoBeanDaoConfig.clearIdentityScope();
    }

    public TestBeanDao getTestBeanDao() {
        return testBeanDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public GreenDaoBeanDao getGreenDaoBeanDao() {
        return greenDaoBeanDao;
    }

}
